services:
  app:
    build: .
    env_file:
      - ./.env  # Ele usa o .env local no diretório onde o Docker Compose está rodando
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env  # Monta o .env dentro do contêiner para uso pela aplicação